apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapper
  template:
    metadata:
      labels:
        app: scrapper
    spec:
      containers:
        - image: fdemsar/scrapper
          name: scrapper
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 40
            periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /health/ready
                port: server
              initialDelaySeconds: 40
              periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: scrapper
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: scrapper
